---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: add jumphost to hostvars
      add_host:
          hostname: "192.168.121.1"
          ansible_host: "jumphost"

    - name: delete existing known hosts file
      file: path="{{ ansible_user_dir }}/.ssh/known_hosts" state=absent

    - name: get host key of jumphost
      command: ssh-keyscan jumphost"
      register: jumphost_fingerprint

    - name: add jumphost host key to awx user known hosts
      known_hosts:
        key: "{{ jumphost_fingerprint }}"
      name: jumphost

    - include: create_host_entry.yml
      with_items: "{{ groups['all'] }}"

    - fail: msg="stop here"


