---
- hosts: localhost
  connection: local
  tasks:
    - name: create several ssh docker containers
      docker_container:
        state: "{{ docker_ops  | default('started') }}"
        name: "ts{{ item }}"
        image: linuxsimba/debian-python-and-ssh
        ports:
          - "9{{ item }}:22"
        env:
          AUTHORIZED_KEYS="{{ lookup('file', './keys/ansible_test.pub')}}"
      with_sequence: start=1 end="{{ docker_count|default(18) }}" format='%03d'
